package com.bluntsoftware.devapptv.modules.devapptv.repository;

import com.bluntsoftware.devapptv.modules.devapptv.domain.Artist;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Artist.
* @author autogenerated
*/

@Repository("devapptvArtistRepository")
@Qualifier("devapptv")
//@RepositoryRestResource(collectionResourceRel="devapptv.Artist", path="devapptv/Artist")
public interface ArtistRepository extends GenericRepository<Artist,Integer>  {

}