package com.bluntsoftware.devapptv.modules.devapptv.repository;

import com.bluntsoftware.devapptv.modules.devapptv.domain.Course;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Course.
* @author autogenerated
*/

@Repository("devapptvCourseRepository")
@Qualifier("devapptv")
//@RepositoryRestResource(collectionResourceRel="devapptv.Course", path="devapptv/Course")
public interface CourseRepository extends GenericRepository<Course,Integer>  {

}