package com.bluntsoftware.devapptv.modules.devapptv.repository;

import com.bluntsoftware.devapptv.modules.devapptv.domain.CourseVideo;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: CourseVideo.
* @author autogenerated
*/

@Repository("devapptvCourseVideoRepository")
@Qualifier("devapptv")
//@RepositoryRestResource(collectionResourceRel="devapptv.CourseVideo", path="devapptv/CourseVideo")
public interface CourseVideoRepository extends GenericRepository<CourseVideo,Integer>  {

}